export type EvoRequirements = {
  level?: number;
  attack?: number;
  defense?: number;
  spirit?: number;
  speed?: number;
  aptitude?: number;
  friendship?: number;
  befriended?: string[];
  currentlyOwns?: string[];
  holyExp?: number;
  darkExp?: number;
  birdExp?: number;
  aquaExp?: number;
  dragonExp?: number;
  beastExp?: number;
  machineExp?: number;
  insectPlantExp?: number;
  totalExp?: number;
};
